server:
  port: 9291
spring:
  application:
    name: market-api
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root2018
      url: jdbc:mysql://localhost:3306/supermarket_manager?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  redis:
    host: localhost
    port: 16379
    password: 123456
  mvc:
    async:
      request-timeout: 20000
    static-path-pattern: /**
mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
logging:
  level:
    cn.dingli.market.mapper: debug
